#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
.  /etc/os-release

bypassvpn=`uci -q get vpnpolicy.global.service_policy`

if [ "$bypassvpn" = 1 -a "$VERSION" =  18.06 ]; then
	PROG="sudo -g nonevpn /usr/bin/eco /usr/bin/gl-cloud"
else
	PROG="/usr/bin/eco /usr/bin/gl-cloud"
fi

start_service() {
    local server=$(uci -q get gl-cloud.@cloud[0].server)
    local enable=$(uci -q get gl-cloud.@cloud[0].enable)

    mkdir -p /var/run/cloud

    [ "$enable" != "1" ] && return 0

    procd_open_instance
procd_set_param group nonevpn
    procd_set_param command $PROG
    procd_set_param respawn
    procd_close_instance
}
