#!/bin/sh
. /lib/functions/gl_util.sh

logger -t "gl-switch" "$BUTTON ${ACTION}"

action=off

[ "$ACTION" = "pressed" ] && action=on

func=$(uci -q get switch-button.@main[0].func) || {
    logger -t "gl-switch" "no config"
    exit 0
}

[ -x /etc/gl-switch.d/$func.sh ] || {
    logger -t "gl-switch" "/etc/gl-switch.d/$func.sh can't be exec"
    exit 0
}

if [ "$action" == "on" ]; then
    if [ "$func" == "wireguard" ]; then
      mcu_send_message "Turning WG ON" "wireguard"
    elif [ "$func" == "openvpn" ]; then
      mcu_send_message "Turning OVPN ON" "openvpn"
    elif [ "$func" == "tor" ]; then
      mcu_send_message "Turning TOR ON"
    fi
elif [ "$action" == "off" ]; then
    if [ "$func" == "wireguard" ]; then
      mcu_send_message "Turning WG OFF" "wireguard"
    elif [ "$func" == "openvpn" ]; then
      mcu_send_message "Turning OVPN OFF" "openvpn"
    elif [ "$func" == "tor" ]; then
      mcu_send_message "Turning TOR OFF"
    fi
fi

flock /var/lock/gl-switch.lock "/etc/gl-switch.d/$func.sh" $action &
