#!/bin/sh /etc/rc.common

START=15
STOP=10

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/lua /usr/sbin/repeater
	procd_set_param respawn 3600 2 0
	procd_close_instance
}

stop_service() {
	ubus call repeater stop
}
