#!/bin/sh

# include netifd library
. /lib/netifd/netifd-proto.sh
. /lib/functions/gl_util.sh

logger -t ovpnclient-down "env value:"`env`

interface="$1"

proto_init_update "*" 0                                                              
proto_send_update "$interface"

fix_ovpn_dns_leak

echo "connecting" > /tmp/ovpnclient/${interface}_state
[ -f "/tmp/dnsmasq.d/resolv.vpn" ] && {
	rm /tmp/dnsmasq.d/resolv.vpn
	create_restart_service /etc/init.d/dnsmasq
}
#ifup "$interface"

exit 0
